name: ai_gym_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==1.3.0
      - aiohttp==3.8.4
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - airportsdata==20241001
      - annotated-types==0.7.0
      - anyio==3.7.0
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asgiref==3.8.1
      - astor==0.8.1
      - asttokens==2.2.1
      - async-lru==2.0.2
      - async-timeout==4.0.2
      - attrs==22.2.0
      - azure-core==1.30.2
      - azure-identity==1.17.1
      - babel==2.12.1
      - backcall==0.2.0
      - backoff==2.2.1
      - bardapi==0.1.38
      - bcrypt==4.2.1
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.45.1
      - blake3==1.0.4
      - bleach==6.0.0
      - browser-cookie3==0.19.1
      - build==1.2.2.post1
      - cachetools==5.3.1
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorful==0.5.6
      - comm==0.1.3
      - compressed-tensors==0.9.1
      - contourpy==1.1.0
      - cryptography==42.0.8
      - cycler==0.11.0
      - dataclasses-json==0.5.7
      - debugpy==1.6.7
      - decorator==5.1.1
      - deep-translator==1.11.1
      - deepspeed==0.16.4
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.9
      - diskcache==5.6.1
      - distlib==0.3.9
      - distro==1.9.0
      - duckduckgo-search==8.0.0
      - durationpy==0.9
      - einops==0.8.1
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastapi==0.115.8
      - fastjsonschema==2.17.1
      - filelock==3.17.0
      - filetype==1.2.0
      - flash-attn==2.7.4.post1
      - flask==2.2.3
      - flask-login==0.6.2
      - flask-sqlalchemy==3.0.3
      - flatbuffers==25.2.10
      - fonttools==4.40.0
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2024.12.0
      - gguf==0.10.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.2
      - google-api-python-client==2.169.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.3
      - google-cloud-translate==3.20.2
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - greenlet==2.0.2
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.70.0
      - grpcio-status==1.59.0
      - h11==0.14.0
      - h2==4.1.0
      - hjson==3.1.0
      - hpack==4.0.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.27.1
      - humanfriendly==10.0
      - hyperframe==6.0.1
      - idna==3.4
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - interegular==0.3.3
      - ipykernel==6.23.2
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jeepney==0.8.0
      - jinja2==3.1.2
      - jiter==0.8.2
      - joblib==1.2.0
      - json5==0.9.14
      - jsonlines==3.1.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.6.3
      - jupyter-lsp==2.2.0
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.23.0
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - kubernetes==32.0.1
      - langchain==0.3.13
      - langchain-chroma==0.2.2
      - langchain-community==0.3.13
      - langchain-core==0.3.33
      - langchain-experimental==0.3.4
      - langchain-google-genai==2.0.7
      - langchain-openai==0.3.3
      - langchain-text-splitters==0.3.4
      - langdetect==1.0.9
      - langsmith==0.2.4
      - lark==1.2.2
      - llama-cpp-python==0.1.59
      - lm-format-enforcer==0.10.10
      - lxml==5.3.2
      - lz4==4.3.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistral-common==1.5.3
      - mistune==3.0.1
      - mmh3==5.1.0
      - modelscope==1.23.1
      - monotonic==1.6
      - mpmath==1.3.0
      - msal==1.29.0
      - msal-extensions==1.2.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.6.0
      - nbformat==5.9.0
      - nest-asyncio==1.5.6
      - networkx==3.0
      - ninja==1.11.1.3
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numexpr==2.8.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - onnxruntime==1.20.1
      - openai==1.58.1
      - openapi-schema-pydantic==1.2.4
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.30.0
      - opentelemetry-exporter-otlp-proto-common==1.30.0
      - opentelemetry-exporter-otlp-proto-grpc==1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-asgi==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-proto==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opentelemetry-util-http==0.51b0
      - orjson==3.10.12
      - outlines==0.1.11
      - outlines-core==0.1.26
      - overrides==7.3.1
      - packaging==24.2
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - parsy==2.1
      - partial-json-parser==0.2.1.1.post5
      - patsy==1.0.1
      - peft==0.7.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==2.10.0
      - posthog==3.14.2
      - primp==0.14.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - prompt-toolkit==3.0.38
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - prototxt-parser==1.0
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pycparser==2.21
      - pycryptodomex==3.19.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.0
      - pygments==2.15.1
      - pyjwt==2.8.0
      - pyodbc==4.0.39
      - pyparsing==3.1.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyrsistent==0.19.3
      - pytest==8.3.4
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytz==2022.7.1
      - pyyaml==6.0
      - pyzmq==25.1.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - ray==2.42.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - send2trash==1.8.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - simphile==1.0.2
      - six==1.16.0
      - smart-open==7.1.0
      - sniffio==1.3.0
      - socksio==1.0.0
      - soupsieve==2.4.1
      - sqlalchemy==1.4.47
      - stack-data==0.6.2
      - starlette==0.45.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tenacity==9.0.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tiktoken==0.8.0
      - tinycss2==1.2.1
      - tokenizers==0.21.0
      - tomli==2.0.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.49.0
      - transformers-stream-generator==0.0.5
      - triton==3.1.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - typing-inspect==0.8.0
      - typing-inspection==0.4.0
      - umap==0.1.1
      - uri-template==1.2.0
      - uritemplate==4.1.1
      - urllib3==1.26.15
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.2
      - vllm==0.7.2
      - waitress==2.1.2
      - watchfiles==1.0.4
      - wcwidth==0.2.6
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.6.0
      - websockets==15.0
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.7
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.13
      - yarl==1.8.2
      - zipp==3.21.0