apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
        env: dev
    spec:
      nodeSelector:
        app: analytics
        env: dev
      containers:
      - name: analytics
        image: alpine:latest  
        command: ["sh", "-c", "apk add --no-cache curl && sleep 3600"]
