apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        env: prod
    spec:
      nodeSelector:  # Ensure scheduling to the control-plane node
        app: payment
        env: prod
      containers:
      - name: payment
        image: nginx  # Replace with your payment service image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Access via node port 30080