apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: checkoutservice
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: adservice
  - to:
    - podSelector:
        matchLabels:
          app: shippingservice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - port: 5050
      protocol: UDP
  podSelector:
    matchLabels:
      app: checkoutservice
  policyTypes:
  - Ingress
  - Egress
